@baseUrl = http://localhost:30027

###


###

GEt {{baseUrl}}/videos

###
POST {{baseUrl}}/videos
Content-Type: application/json

{
    "video":"bonjour",
    "expediteur": "k1"
}
###
PUT {{baseUrl}}/videos/10